
import pandas as pd
s1 = pd.Series([1,2,3,4,5,None,2], index=['a','b','c','d','e','f','g'])
print(s1.head())  
print(s1.tail())
print(s1.describe())
print(s1.shape)
print(s1.size)
print(s1.ndim)
print(s1.dtype)
print(s1.index)
print(s1.values)
print(s1.index.name)
print(s1.count())
print(s1.prod())
print(s1.max())
print(s1.min())
print(s1.mean())
print(s1.median())
print(s1.mode())
print(s1.describe())